application: ninja-ide-irc
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /raw
  static_dir: logs

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
